-- Create the certificates table
CREATE TABLE certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name TEXT NOT NULL,
  score BIGINT NOT NULL,
  total BIGINT NOT NULL,
  percentage TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (since users don't log in)
CREATE POLICY "Allow anonymous inserts" 
ON certificates 
FOR INSERT 
WITH CHECK (true);

-- Allow public read access (for the leaderboard)
CREATE POLICY "Allow public read access" 
ON certificates 
FOR SELECT 
USING (true);
